### ISSUE TITLE
RADAR data

### ISSUE THREAD

**Issue by timkeane** [Oojimentis/uat978_wx_test#2]
Hi Trevor... This is Jeff's friend Tim.  He mentioned your trouble with the RADAR data.  I suspect the point data you have represents either the top right corner or the center of a raster cell while the intensity is the value of the cell.  The resolution of the data should be the width and height of the cell if you have that info.  You could probably draw the data on the map as vector squares color coded by the intensity value rather than create a raster dataset if the resolution is not too fine.

**Comment by Oojimentis** [comment]
Hey Tim how have you been?  Hope all is well? This GIS stuff is like black magic!  I did try adding the points as vector squares but the amount of data I'm adding brought the browser to its knees - 60k points! I originally thought this would be an easy thing to do. I have a vague idea of exporting the postgres raster to a WMS  (would GEOserver do this?) and then accessing the WMS from Leaflet - does that sound feasible?  Any clues would be appreciated.  
Hoping we can all get together for a beer again soon. T.

**Comment by timkeane** [comment]
you can definitely serve the raster through geoserver and i may be able to
help you w that.  the export to raster from postgis is something i am not
too familiar with.  have you looked at gdal for creating the raster? there
are definitely tools in there that can do it

**Comment by timkeane** [comment]
and if you want to just chat about this you can give me a call at
917-239-3441 - hit me w a text first so i know its you

**Comment by Oojimentis** [comment]
Hi Tim - thanks to your suggestions I think I have this just about working now. There's an option in Leaflet to render via a canvas - not exactly sure what that is, but the browser can now handle the 1000's of rectangles I'm throwing at it. (I also filtered the amount of data coming over from Postgresql).
So - thanks for the help and hope to see you and Jeff for a beer or two sometime soon. T.

**Comment by timkeane** [comment]
canvas is an html5 dom element.  i thought that was the default option at
this point
